/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminScoresRouteImport } from './routes/admin.scores'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAcceptInviteRouteImport } from './routes/admin.accept-invite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScoresRoute = AdminScoresRouteImport.update({
  id: '/admin/scores',
  path: '/admin/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcceptInviteRoute = AdminAcceptInviteRouteImport.update({
  id: '/admin/accept-invite',
  path: '/admin/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/team': typeof AdminTeamRoute
  '/exam/$examId': typeof ExamExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/team': typeof AdminTeamRoute
  '/exam/$examId': typeof ExamExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/accept-invite': typeof AdminAcceptInviteRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scores': typeof AdminScoresRoute
  '/admin/team': typeof AdminTeamRoute
  '/exam/$examId': typeof ExamExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/accept-invite'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/login'
    | '/admin/scores'
    | '/admin/team'
    | '/exam/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/accept-invite'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/login'
    | '/admin/scores'
    | '/admin/team'
    | '/exam/$examId'
  id:
    | '__root__'
    | '/'
    | '/admin/accept-invite'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/login'
    | '/admin/scores'
    | '/admin/team'
    | '/exam/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAcceptInviteRoute: typeof AdminAcceptInviteRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminScoresRoute: typeof AdminScoresRoute
  AdminTeamRoute: typeof AdminTeamRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scores': {
      id: '/admin/scores'
      path: '/admin/scores'
      fullPath: '/admin/scores'
      preLoaderRoute: typeof AdminScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accept-invite': {
      id: '/admin/accept-invite'
      path: '/admin/accept-invite'
      fullPath: '/admin/accept-invite'
      preLoaderRoute: typeof AdminAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAcceptInviteRoute: AdminAcceptInviteRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminScoresRoute: AdminScoresRoute,
  AdminTeamRoute: AdminTeamRoute,
  ExamExamIdRoute: ExamExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
